services:
  db:
    image: postgres:16.4
    container_name: postgres_db
    restart: unless-stopped
    ports:
      - "5433:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
    env_file:
      - ./.env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  data: