services:
  app:
    container_name: weather-viewer-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:8080"
    env_file:
      - ./.env
    depends_on:
      db:
        condition: service_healthy
    restart: always

  db:
    image: postgres:16.4
    container_name: postgres_db
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./.env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  postgres_data: